### PR TITLE
Merge upstream v0.196.2

### PR DESCRIPTION
**Pull request by aliculPix4D**
- merge upstream changes (v0.196.2)
- ci: `github_ssh_key_base64` instead of removed `concourse_janus` one.

### CODE REVIEW

**Comment by Pix4D-Janus** [comment]
pipeline_setter_bot: your pipeline is set: https://builder.ci.pix4d.com/teams/developers/pipelines/dependabot-merge-upstream-v0.196.2

**Comment by Esysc** [comment]
It didn't pass the check, do you have any idea?

**Comment by aliculPix4D** [comment]
> It didn't pass the check, do you have any idea?

Super strange, because locally building the image works without issues. I re-triggered the job.

**Comment by aliculPix4D** [comment]
Closing this PR. There is a new version out upstream.

**Pull request closed without merging**
