### PR TITLE
Fix git conflicts latest

### PR DESCRIPTION
**Pull request by aliculPix4D**
- automatic merge failed:
https://builder.ci.pix4d.com/teams/developers/pipelines/dependabot-master/jobs/merge-upstream/builds/119#L60575192:265

### CODE REVIEW

**Comment by Pix4D-Janus** [comment]
Your pipeline is set.
Check it here:https://builder.ci.pix4d.com/teams/developers/pipelines/dependabot-fix-git-conflicts-latest

**Comment by aliculPix4D** [comment]
It seems that upstream they are not so strict (as we are) anymore with rubocop linter tests:
https://github.com/dependabot/dependabot-core/runs/2299062619#step:9:368

Since this is the only reason our "tests" are failing, I am now wondering what is the best way to proceed:
https://builder.ci.pix4d.com/teams/developers/pipelines/dependabot-fix-git-conflicts-latest/jobs/test-dependabot/builds/1#L60575879:616

**Comment by marco-m-pix4d** [comment]
If I understand correctly, the root of the problem is that upstream still merges into master code that breaks tests, while we don't.

Considering that the breaking tests are rubocop-only, I think we could rationalize that if the code is good enough for upstream, it is good enough for us also. Again, considering the specific class of failing tests.

So one way to proceed could be, if rubocop supports it, to split the rubocop tests in 2 sets: one set contains files that we never touch, the other set contains files that we touch.

For the first set, we disable rubocop.

For the second set, we keep rubocop and hope that upstream will break this set less often.

Does it make sense?

**Comment by aliculPix4D** [comment]
> Does it make sense?

Yes. I added a commit with following changes:
```
      cd dependabot-core.git/pix4d-dependabot
      bundle exec rubocop -c . ../python ../docker
```
hence only files in these three directories (pix4d-dependabot, python and docker) will be checked with rubocop

**Comment by aliculPix4D** [comment]
@Pix4D/integration can you review the PR please.

**Review by odormond — APPROVED** [review]

**Review by Esysc — APPROVED** [review]

**Pull request merged**
